import './about-us.schema';
import './course-participents.schema';
import './course.schema';
import './events.schema';
import './main-page.schema';
import './portfolio.schema';
import './project-participents.schema';
import './static_sections.schema';
import './user.schema';
